app/__init__.py
import os, secrets
from flask import Flask
from config import Config
from datetime import datetime

app = Flask(__name__, static_url_path='/static')

default_secret_key = secrets.token_hex(8)
app.secret_key = os.getenv('SECRET_KEY', default_secret_key)
# First, define filters
@app.template_filter('format_date')
def format_date(value):
    if isinstance(value, datetime):
        return value.strftime('%m-%d-%Y')
    return value

@app.template_filter('format_time')
def format_time(time_str):
    time_obj = datetime.strptime(time_str, '%H:%M')
    return time_obj.strftime('%I:%M %p')

@app.template_filter('format_reservation_type')
def format_reservation_type(type_str):
    return ' '.join(word.capitalize() for word in type_str.split('_'))

app.config.from_object(Config)

@app.context_processor
def inject_nav_items():
    return dict(nav_items=Config.NAVIGATION_ITEMS)

from app.routes import index

app.jinja_env.filters['format_date'] = format_date
app.jinja_env.filters['format_time'] = format_time
app.jinja_env.filters['format_reservation_type'] = format_reservation_type

app.register_blueprint(index.bp)

app/routes/__init__.py
# no code needed here for the time being

app/routes/index.py
# index.py
import os, secrets
from flask import Blueprint, request, current_app, redirect, url_for, flash
from datetime import datetime
from app.utils import (if_validated_reserve, 
write_record_to_json, render_page, count_records,
generate_sample_data, update_record_by_hash_key, 
delete_record_by_hash_key, get_record_by_hash_key, 
get_json_data )

from config import Config

bp = Blueprint('main', __name__)

@bp.route('/error')
def error():
    return render_page('pages/error.html', "Error")


@bp.route('/')
@bp.route('/<page_name>')
def main(page_name='home'):
    if page_name not in current_app.config['ALLOWED_PAGES']:
        return redirect(url_for('main.error'))

    template_path = 'pages/main.html' if page_name == 'home' else f'pages/{page_name}.html'
    template_full_path = os.path.join(current_app.root_path, 'templates', template_path)

    if os.path.exists(template_full_path):
        return render_page(template_path, page_name.capitalize())
    else:
        return redirect(url_for('main.error'))
    


@bp.route('/reserve', methods=['GET', 'POST'])
def reserve():
    if request.method == 'POST':
        if count_records(Config.DATA_FILE) >= 10:
            flash('Sorry, we have reached the maximum number of reservations.', 'error')
            return redirect(url_for('main.error'))

        reservation_data = request.form.to_dict()
        is_valid, message = if_validated_reserve(reservation_data)
        if not is_valid:
            flash(message, 'error')
            return redirect(url_for('main.reserve'))

        try:
            reservation_data['reservation_key'] = secrets.token_hex(3)  # Unique 6-character key
            write_record_to_json(reservation_data, Config.DATA_FILE)
            return render_page('pages/reservation.html', 'Reservation Confirmed', reservation_data=reservation_data)
        except Exception as e:
            current_app.logger.error(f"Error during reservation: {e}")
            flash('There was an error processing your reservation. Please try again.', 'error')
            return redirect(url_for('main.reserve'))

    reservation_types = current_app.config['RESERVATION_TYPES']
    return render_page('pages/reserve.html', 'Make a Reservation', reservation_types=reservation_types)



@bp.route('/reservations', methods=['GET'])
def reservations():
    DATA_FILE = Config.DATA_FILE
    RESERVATION_TYPES = current_app.config['RESERVATION_TYPES']

    if not os.path.isfile(DATA_FILE):
        generate_sample_data(RESERVATION_TYPES, DATA_FILE)

    reservations = get_json_data(DATA_FILE)
    if len(reservations) < 3:
        generate_sample_data(RESERVATION_TYPES, DATA_FILE)
        reservations = get_json_data(DATA_FILE)

    return render_page('pages/reservations.html', 'Upcoming Appointments', reservations=reservations)




@bp.route('/reservations/update/<hash_key>', methods=['POST'])
def update_reservation(hash_key):
    updated_data = {
        'first_name': request.form['first_name'],
        'last_name': request.form['last_name'],
        'email': request.form['email'],  # Ensure 'email' is used here
        'reservation_type': request.form['reservation_type'],
        'reservation_date': request.form['reservation_date'],
        'reservation_time': request.form['reservation_time']
    }

    update_record_by_hash_key(hash_key, updated_data, Config.DATA_FILE)
    return redirect(url_for('main.reservations'))



@bp.route('/reservations/delete/<hash_key>', methods=['POST'])
def delete_reservation_action(hash_key):
    if delete_record_by_hash_key(hash_key, Config.DATA_FILE):
        flash('Reservation deleted successfully.', 'success')
    else:
        flash('Reservation not found.', 'error')
    return redirect(url_for('main.reservations'))



@bp.route('/reservations/edit/<hash_key>', methods=['GET', 'POST'])
def edit_reservation(hash_key):
    if request.method == 'POST':
        try:
            updated_data = {
                'first_name': request.form['first_name'],
                'last_name': request.form['last_name'],
                'email': request.form['email'],
                'reservation_type': request.form['reservation_type'],
                'reservation_date': request.form['reservation_date'],
                'reservation_time': request.form['reservation_time']
            }
            update_record_by_hash_key(hash_key, updated_data, Config.DATA_FILE)
            return redirect(url_for('main.reservations'))
        except Exception:
            return render_page('pages/error.html', 'Error', error_message="An error occurred while updating the reservation.")

    reservation = get_record_by_hash_key(hash_key)
    
    if reservation is None:
        return redirect(url_for('main.reservations'))

    reservation_types = current_app.config['RESERVATION_TYPES']
    return render_page('pages/edit_reservation.html', 'Edit Reservation', reservation=reservation, reservation_types=reservation_types)



@bp.route('/reservations/confirm_delete/<hash_key>', methods=['GET'])
def confirm_delete_reservation(hash_key):
    reservation = get_record_by_hash_key(hash_key)
    
    if reservation:
        # Ensure the date is a datetime object
        if isinstance(reservation['reservation_date'], str):
            reservation['reservation_date'] = datetime.strptime(reservation['reservation_date'], '%Y-%m-%d')
        
        return render_page('pages/delete_reservation.html', 'Confirm Delete Reservation', reservation=reservation)
    
    flash('Reservation not found.', 'error')
    return redirect(url_for('main.reservations'))

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ website_name }} - {{ page_title }}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Your Custom CSS (Always loaded) -->
    <link href="{{ url_for('static', filename='css/layout.css') }}" rel="stylesheet">

    <!-- Page-specific CSS -->
    {% if css_file %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/' ~ body_class ~ '.css') }}">
    {% endif %}
</head>
<body class="{% block body_class %}{% endblock %}">

    {% include 'navbar.html' %}

    <main class="p-4">
        {% block content %}
            <!-- Page-specific content will be inserted here -->
        {% endblock %}
    </main>

    {% block scripts %}
        {% if body_class %}
            <script src="{{ url_for('static', filename='js/' ~ body_class ~ '.js') }}"></script>
        {% endif %}
    {% endblock %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Your Custom JavaScript (Always loaded) -->
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
</body>
</html>

app/templates/navbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
            <!-- Navbar Brand -->
            <a class="navbar-brand" href="{{ url_for('main.main', page_name='home') }}">{{ config.WEBSITE_NAME }}</a>
  
            <!-- Navbar Toggle Button for Mobile -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
  
            <!-- Navbar Links -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <!-- Mobile menu -->
                <ul class="navbar-nav d-lg-none">
                    {% for url, name in nav_items %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.main', page_name=url.strip('/')) }}">{{ name }}</a>
                    </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact</a>
                    </li>
                </ul>

                <!-- Links for medium and large screens -->
                <ul class="navbar-nav centered d-none d-lg-flex">
                    {% for url, name in nav_items %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.main', page_name=url.strip('/')) }}">{{ name }}</a>
                    </li>
                    {% endfor %}
                </ul>
                <ul class="navbar-nav right d-none d-lg-flex">
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/templates/pages/contact.html
{% extends "layout.html" %}

{% set body_class = "contact" %}

{% block content %}
<div class="contact-card">
    <ul>
        <li>
            <a href="https://www.linkedin.com/" target="_blank">
                 Connect on LinkedIn
            </a>
        </li>
        <li>
            <a href="https://github.com/" target="_blank">
                See code in GitHub
            </a>
        </li>
        <li>
            <a href="mailto:example@exmaple.com">
                 Send an Email
            </a>
        </li>
    </ul>
</div>

{% endblock %}

app/templates/pages/delete_reservation.html
{% extends "layout.html" %}

{% set body_class = "delete_reservation" %}

{% block content %}
<div class="confirm-delete">
    <h1 class="dashboard-title">Confirm Delete?</h1>
    <div class="horizontal-line"></div>
    <form action="{{ url_for('main.delete_reservation_action', hash_key=reservation.reservation_key) }}" method="post">
        <div class="content">
            <div class="delete-record">
                <div>
                    <label for="first_name">First Name:</label>
                    <p>{{ reservation.first_name }}</p>
                </div>
                
                <div>
                    <label for="last_name">Last Name:</label>
                    <p>{{ reservation.last_name }}</p>
                </div>
                
                <div>
                    <label for="email">Email:</label>
                    <p>{{ reservation.email }}</p>
                </div>
                
                <div>
                    <label for="reservation_type">Reservation Type:</label>
                    <p>{{ reservation.reservation_type }}</p>
                </div>
                
                <div>
                    <label for="reservation_date">Reservation Date:</label>
                    <p>{{ reservation.reservation_date|format_date }}</p>
                </div>
                
                <div>
                    <label for="reservation_time">Reservation Time:</label>
                    <p>{{ reservation.reservation_time|format_time }}</p>
                </div>
                
                <div>
                    <label for="hash_key">Reservation Key:</label>
                    <p>{{ reservation.reservation_key }}</p>
                </div>
                
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/pages/edit_reservation.html
{% extends "layout.html" %}

{% set body_class = "edit_reservation" %}

{% block content %}
    <div class="content">
        <h1>Edit Reservation</h1>
        <form action="{{ url_for('main.edit_reservation', hash_key=reservation.reservation_key) }}" method="POST">
            <label for="first_name">First Name:</label>
            <input type="text" name="first_name" id="first_name" value="{{ reservation.first_name }}" required>

            <label for="last_name">Last Name:</label>
            <input type="text" name="last_name" id="last_name" value="{{ reservation.last_name }}" required>

            <label for="email">Email Address:</label>
            <input type="email" name="email" id="email" value="{{ reservation.email }}" required>

            <label for="reservation_type">Reservation Type:</label>
            <select name="reservation_type" id="reservation_type" required>
                <option value="">Select a Reservation Type</option>
                {% for value, label in reservation_types %}
                    <option value="{{ value }}" {% if reservation.reservation_type == value %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>

            <label for="reservation_date">Reservation Date:</label>
            <input type="date" name="reservation_date" id="reservation_date" value="{{ reservation.reservation_date }}" required>

            <label for="reservation_time">Reservation Time:</label>
            <input type="time" name="reservation_time" id="reservation_time" value="{{ reservation.reservation_time }}" required>

            <button type="submit">Update Reservation</button>
        </form>
    </div>
{% endblock %}

app/templates/pages/error.html
{% extends "layout.html" %}

{% set body_class = "error" %}

{% block content %}
<div class="content">
    <div class="error-container">
        <h1>ERROR</h1>
        <p>The page you are looking for doesn't exist or isn't connected...</p>
    </div>
</div>
{% endblock %}

app/templates/pages/main.html
{% extends "layout.html" %}

{% set body_class = "main" %}

{% block content %}

    <!-- Introduction Section -->
    <section class="intro">
        <h2>Hello, There!</h2>
        <p>I'm excited to share my work and skills with you! I'm a passionate <strong>programmer</strong>, specializing in <strong>python</strong>. I love working on <strong>full stack projects</strong>, and I'm always excited to take on new challenges!</p>
    </section>

    <!-- Skills Section -->
    <section class="skills">
        <h3>Skills</h3>
        <div class="skills-container">
            <div class="skill">
                <h4>Web Development</h4>
                <p>Expertise in HTML, CSS, and Python framework Flask for full stack development. </p>
            </div>
            <div class="skill">
                <h4>Database Management</h4>
                <p>Experience with SQL, PostgreSQL, MongoDB, and efficient data handling.</p>
            </div>
            <div class="skill">
                <h4>Python Programming</h4>
                <p>Advanced skills in Python for scripting, web development, and data analysis.</p>
            </div>
        </div>
    </section>

    <!-- Featured Projects Section -->
    <section class="projects">
        <h3>Featured Projects</h3>
        <div class="projects-container">
            <div class="project">
                <h4>Flask Starter Template</h4>
                <p>Barebone flask starter project with hybrid static/dynamic routing. Best use case for a static website with multiple pages.</p>
                <a href="https://github.com/AbedMahmood/flask_starter_template" class="button" target="_blank">View Project</a>
            </div>
            <div class="project">
                <h4>Flask Reservation App</h4>
                <p>A website to make reservations which demonstrates the understanding of full stack development of a web app.</p>
                <a href="https://github.com/AbedMahmood/flask_reservation_app" class="button" target="_blank">View Project</a>
            </div>
        </div>
    </section>

    <!-- Testimonials Section -->
    <section class="testimonials">
        <h3>What People Are Saying</h3>
        <blockquote>
            <p>"[Your Name] is an incredible [Your Profession]. They delivered great work and exceeded our expectations!"</p>
            <footer>- [Client Name]</footer>
        </blockquote>
    </section>
{% endblock %}

app/templates/pages/reservation.html
{% extends "layout.html" %}

{% set body_class = "reservation" %}

{% block content %}
    <div class="content">
        <h1>{{ page_title }}</h1>

        <h3>Reservation Details</h3>

        <p><strong>First Name:</strong> {{ reservation_data.first_name }}</p>
        <p><strong>Last Name:</strong> {{ reservation_data.last_name }}</p>
        <p><strong>Email:</strong> {{ reservation_data.email }}</p>
        <p><strong>Reservation Type:</strong> {{ reservation_data.reservation_type }}</p>
        <p><strong>Reservation Date:</strong> {{ reservation_data.reservation_date }}</p>
        <p><strong>Reservation Time:</strong> {{ reservation_data.reservation_time }}</p>
        <p><strong>Reservation Key:</strong> {{ reservation_data.reservation_key }}</p>
    </div>
{% endblock %}

app/templates/pages/reservations.html
{% extends "layout.html" %}

{% set body_class = "reservations" %}

{% block content %}
<div class="reservations-dashboard">
    <h1 class="dashboard-title">{{ page_title }}</h1>

    <!-- Reservations Grid -->
    <div class="reservations-grid">
        {% for reservation in reservations %}
            <div class="reservation-card">
                <div class="card-header">
                    <h3>{{ reservation.first_name }} {{ reservation.last_name }}</h3>
                    <span class="reservation-type">{{ reservation.reservation_type|format_reservation_type }}</span>
                </div>
                <div class="card-body">
                    <p><strong>Email:</strong> {{ reservation.email }}</p>
                    <p><strong>Date:</strong> {{ reservation.reservation_date|format_date }}</p>
                    <p><strong>Time:</strong> {{ reservation.reservation_time|format_time }}</p>
                    <p><strong>Reservation Key:</strong> {{ reservation.reservation_key }}</p>
                    <div class="button-container">
                        <a href="{{ url_for('main.edit_reservation', hash_key=reservation.reservation_key) }}" class="btn btn-primary">Update</a>
                        <a href="{{ url_for('main.confirm_delete_reservation', hash_key=reservation.reservation_key) }}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
                
            </div>
        {% else %}
            <p class="no-reservations">No reservations found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/pages/reserve.html
{% extends "layout.html" %}

{% set body_class = "reserve" %}

{% block content %}
<div class="content">
    <h1>{{ page_title }}</h1>
    {% if message %}
        <div class="alert">{{ message }}</div>
    {% endif %}
    <form id="reservationForm" action="{{ url_for('main.reserve') }}" method="POST" formnovalidate>
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name" required>

        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" id="last_name" required>

        <label for="email">Email Address:</label>
        <input type="email" name="email" id="email" required>

        <label for="reservation_type">Reservation Type:</label>
        <select name="reservation_type" id="reservation_type" required>
            <option value="">Select a Reservation Type</option>
            {% for value, label in reservation_types %}
                <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
        </select>

        <label for="reservation_date">Reservation Date:</label>
        <input type="date" name="reservation_date" id="reservation_date" required>

        <label for="reservation_time">Reservation Time:</label>
        <input type="time" name="reservation_time" id="reservation_time" required>

        <button type="submit">Reserve</button>
    </form>
</div>
{% endblock %}

app/templates/pages/test.html
{% extends "layout.html" %}

{% set body_class = "test" %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <p>This is the test page of my website for static website</p>
{% endblock %}